name: stacked
description: The framework to build testable, scalable and maintainable flutter apps
version: 3.1.2
homepage: https://stacked.filledstacks.com/
repository: https://github.com/Stacked-Org/stacked.git
issue_tracker: https://github.com/Stacked-Org/stacked/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.1.4
  meta: ^1.3.0
  provider: ^6.0.0
  collection: ^1.15.0
  stacked_core: ^1.2.4
  universal_io: ^2.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
