name: stacked
description: An architecture and widgets for an MVVM inspired architecture in Flutter. It provides common functionalities required to build a large application in a understandable manner.
version: 1.9.6
homepage: https://github.com/FilledStacks/stacked

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.1
  observable_ish: ^2.1.4
  meta: ^1.1.8
  get_it: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter