name: stacked_cli
description: The official stacked cli to improve the stacked dev experience
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  args: ^2.3.0
  get_it: ^7.2.0
  mockito: ^5.0.17
  mustache_template: ^2.0.0
  recase: ^4.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  
  build_runner: ^2.1.7
