name: stacked_cli
description: The official dev tools for the Stacked Framework
version: 1.1.12
homepage: https://stacked.filledstacks.com/docs/stacked-cli
repository: https://github.com/FilledStacks/stacked/tree/master/packages/stacked_cli

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.3.0
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  mockito: ^5.0.17
  mustache_template: ^2.0.0
  path: ^1.8.1
  pubspec_yaml: ^3.1.0
  recase: ^4.0.0
  json_annotation: ^4.7.0
  ansicolor: ^2.0.1
  xdg_directories: ^0.2.0+2
  usage: ^4.1.0
  pub_updater: ^0.2.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

executables:
  stacked:
