name: stacked_generator
description: Stacked Generator is a package dedicated to reduce the boilerplate required to setup a stacked application
version: 0.1.0
homepage: https://github.com/Milad-Akarie/auto_route_library

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.0.0
  source_gen: ^0.9.0
  analyzer: ">=0.39.2 <0.40.0"
  path: ^1.6.4
  logger: ^0.9.0

  stacked:
    path: ../stacked

dev_dependencies:
  build_runner: ^1.0.0
  source_gen_test:
  test:
