name: stacked_generator
description: Stacked Generator is a package dedicated to reduce the boilerplate required to setup a stacked application
version: 0.6.2
homepage: https://github.com/FilledStacks/stacked/tree/master/packages/stacked_generator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  build: ^2.2.1
  source_gen: ^1.2.1
  analyzer: ^3.1.0
  path: ^1.8.0
  # logger: ^1.0.0
  recase: ^4.0.0
  # Remove the path and use pub one after publish the stacked_core
  stacked_core:
    path: ../stacked_core

dev_dependencies:
  build_runner: ^2.0.6
  source_gen_test: ^1.0.0
  test:
