name: stacked_generator
description: Stacked Generator is a package dedicated to reduce the boilerplate required to setup a stacked application
version: 0.7.11
homepage: https://github.com/FilledStacks/stacked/tree/master/packages/stacked_generator

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  build: ^2.2.1
  path: ^1.8.0
  recase: ^4.0.0
  source_gen: ^1.2.2
  meta: ^1.7.0
  logger: ^1.1.0
  stacked_core: ^1.2.3
  # Removing this will cause issues when publish the package
  analyzer: ^4.1.0

dev_dependencies:
  build_runner: ^2.0.6
  test: ^1.20.1
  build_test: ^2.1.5
