name: stacked_generator
description: Stacked Generator is a package dedicated to reduce the boilerplate required to setup a stacked application
version: 0.3.1-nullsafety.4
homepage: https://github.com/FilledStacks/stacked/tree/master/packages/stacked_generator

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  build: ^2.0.0
  source_gen: ^1.0.0
  analyzer: ^1.3.0
  path: ^1.6.4
  # logger: ^0.9.0
  recase: ^4.0.0-nullsafety.0
  stacked:
    ^2.0.0
    # path: ../stacked

dev_dependencies:
  build_runner: ^1.11.5
  source_gen_test: ^1.0.0
  test:
