name: stacked_generator
description: Stacked Generator is a package dedicated to reduce the boilerplate required to setup a stacked application
version: 0.2.6
homepage: https://github.com/FilledStacks/stacked/tree/master/packages/stacked_generator

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.0.0
  source_gen: ^0.9.0
  analyzer: ^1.1.0
  path: ^1.6.4
  # logger: ^0.9.0
  recase: ^3.0.1
  stacked: ^1.9.5
    # path: ../stacked

dev_dependencies:
  build_runner: ^1.11.5
  source_gen_test:
  test:
